const products = [
  {
    id: 1,
    name: "Apple iMac 27, 1TB HDD, Retina 5K",
    price: 169999,
    originalPrice: 1999,
    discount: "35% OFF",
    rating: 5.0,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Desktops/Images/311754_0_p4etiv.png",
    isBestSeller: true,
    brand: "Apple",
    category: "Desktop",
  },

  {
    id: 2,
    name: "Apple iPhone 17 Pro Max, 1TB",
    price: 129999,
    originalPrice: 1500,
    rating: 4.0,
    discount: "15% OFF",
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/317417_0_7ISiBcc4Y.png?updatedAt=1757529273198",
    isBestSeller: true,
    brand: "Apple",
    category: "Phone",
  },
  {
    id: 3,
    name: "iPad Pro 13-Inch (M4): XDR Display, 512GB",
    price: 89999,
    rating: 4.9,
    discount: "35% OFF",
    image:
      "https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/264226_fefcjf.png",
    brand: "Apple",
    category: "Tablet",
  },
  {
    id: 4,
    name: "Samsung S25 Ultra, 1TB",
    price: 129999,
    originalPrice: 1500,
    rating: 4.9,
    discount: "15% OFF",
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/316059_0_q4clnn.png",
    isBestSeller: true,
    brand: "Samsung",
    category: "Phone",
  },
  {
    id: 5,
    name: "PlayStation 5 Console - 1TB, PRO Controller",
    price: 68999,
    rating: 4.8,
    discount: "10% OFF",
    image:
      "https://media.tatacroma.com/Croma%20Assets/Gaming/Gaming%20Consoles/Images/305985_ilpfe3.png",
    brand: "Sony",
    category: "Gaming",
  },

  {
    id: 6,
    name: "Samsung Galaxy S25 Ultra",
    price: 124999,
    originalPrice: 144999,
    discount: "14% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/316059_0_q4clnn.png",
    isBestSeller: true,
    brand: "Samsung",
    category: "Phone",
  },
  {
    id: 7,
    name: "iPhone 14 Plus Blue",
    price: 69900,
    originalPrice: 79900,
    discount: "12% OFF",
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/261949_0_o0rd9d.png",
    brand: "Apple",
    category: "Phone",
  },
  {
    id: 8,
    name: "Google Pixel 8 Pro",
    price: 93999,
    originalPrice: 106999,
    discount: "12% OFF",
    rating: 4.5,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/309134_0_cv9vxa.png",
    brand: "Google",
    category: "Phone",
  },
  {
    id: 9,
    name: "Galaxy Z Fold 6",
    price: 164999,
    originalPrice: 174999,
    discount: "6% OFF",
    rating: 4.7,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/308188_0_upzg1b.png",
    brand: "Samsung",
    category: "Phone",
  },

  // --- TABLETS ---
  {
    id: 10,
    name: "iPad Pro 13 (M4)",
    price: 129900,
    originalPrice: 139900,
    discount: "7% OFF",
    rating: 4.9,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/301976_1_qaq6hk.png",
    isBestSeller: true,
    brand: "Apple",
    category: "Tablet",
  },
  {
    id: 11,
    name: "iPad Air 11 (M2)",
    price: 59900,
    originalPrice: 65900,
    discount: "9% OFF",
    rating: 4.7,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/301927_2_rhqs3m.png",
    brand: "Apple",
    category: "Tablet",
  },

  // --- GAMING ---
  {
    id: 12,
    name: "Sony PlayStation 5 Slim",
    price: 49990,
    originalPrice: 54990,
    discount: "9% OFF",
    rating: 4.9,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Gaming/Gaming%20Consoles/Images/305985_ilpfe3.png",
    brand: "Sony",
    category: "Gaming",
  },
  {
    id: 13,
    name: "Xbox Series X",
    price: 48990,
    originalPrice: 55990,
    discount: "12% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Gaming/Gaming%20Consoles/Images/226313_0_nbabpt.png",
    brand: "Microsoft",
    category: "Gaming",
  },
  {
    id: 14,
    name: "PS5 DualSense Controller",
    price: 5900,
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Gaming/Gaming%20Accessories/Images/307145_ood23z.png?tr=w-600",
    brand: "Sony",
    category: "Gaming",
  },
  {
    id: 15,
    name: "Xbox Wireless Controller",
    price: 5390,
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Gaming/Gaming%20Accessories/Images/255992_0_k9x7sq.png",
    brand: "Microsoft",
    category: "Gaming",
  },

  // --- MORE PHONES/COMPUTERS ---
  {
    id: 16,
    name: "Samsung Galaxy S24 FE",
    price: 54999,
    originalPrice: 65999,
    discount: "16% OFF",
    rating: 4.5,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/311523_0_purtk1.png",
    brand: "Samsung",
    category: "Phone",
  },
  {
    id: 17,
    name: "iPhone 13 Starlight",
    price: 49900,
    originalPrice: 59900,
    discount: "17% OFF",
    rating: 4.7,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/243460_0_CILAYIAIB.png?updatedAt=1762431620782",
    brand: "Apple",
    category: "Phone",
  },
  {
    id: 18,
    name: "MacBook Pro 14 M3",
    price: 169900,
    originalPrice: 189900,
    discount: "10% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/305748_nbrbma.png",
    brand: "Apple",
    category: "Laptop",
  },
  {
    id: 19,
    name: "Dell XPS 15",
    price: 240000,
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/255340_0_c2vnaz.png",
    brand: "Dell",
    category: "Laptop",
  },
  {
    id: 20,
    name: "Sony PS5 Digital Edition",
    price: 44990,
    discount: "5% OFF",
    rating: 4.8,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/316841_0_3PBoI2KDZ.png?updatedAt=1762776920489",
    brand: "Sony",
    category: "Gaming",
  },
  {
    id: 21,
    name: "iPhone 15 Pro Max Titanium",
    price: 159900,
    originalPrice: 169900,
    discount: "5% OFF",
    rating: 4.9,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/300828_0_gdtzmh.png",
    isBestSeller: true,
    brand: "Apple",
    category: "Phone",
  },

  // --- CAMERAS ---
  {
    id: 22,
    name: "Canon EOS R5 Full Frame Mirrorless Camera",
    price: 339990,
    originalPrice: 369990,
    discount: "8% OFF",
    rating: 4.9,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/DSLR%20and%20Mirrorless%20cameras/Images/228631_0_gslzrl.png",
    isBestSeller: true,
    brand: "Canon",
    category: "Camera",
  },
  {
    id: 23,
    name: "Sony Alpha 7 IV Full Frame Camera",
    price: 242990,
    originalPrice: 269990,
    discount: "10% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/DSLR%20and%20Mirrorless%20cameras/Images/251802_0_cjz5ts.png",
    isBestSeller: true,
    brand: "Sony",
    category: "Camera",
  },
  {
    id: 24,
    name: "Nikon Z8 Full Frame Mirrorless Camera",
    price: 329990,
    originalPrice: 359990,
    discount: "8% OFF",
    rating: 4.9,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/DSLR%20and%20Mirrorless%20cameras/Images/274195_0_epvimr.png",
    brand: "Nikon",
    category: "Camera",
  },
  {
    id: 25,
    name: "Canon EOS 90D DSLR Camera",
    price: 114990,
    originalPrice: 129990,
    discount: "12% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/DSLR%20and%20Mirrorless%20cameras/Images/224549_0_fxz7fd.png",
    brand: "Canon",
    category: "Camera",
  },
  {
    id: 26,
    name: "Sony ZV-E10 Vlogging Camera",
    price: 54990,
    originalPrice: 64990,
    discount: "15% OFF",
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/DSLR%20and%20Mirrorless%20cameras/Images/249095_0_jnsrp7.png",
    brand: "Sony",
    category: "Camera",
  },
  {
    id: 27,
    name: "GoPro HERO12 Black Action Camera",
    price: 44990,
    originalPrice: 49990,
    discount: "10% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Action%20Camera/Images/304139_0_zxzqtc.png",
    isBestSeller: true,
    brand: "GoPro",
    category: "Camera",
  },

  // --- CAMERA LENSES ---
  {
    id: 28,
    name: "Canon RF 24-70mm f/2.8L IS USM Lens",
    price: 219990,
    originalPrice: 239990,
    discount: "8% OFF",
    rating: 4.9,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Lenses/Images/227084_0_nbrxww.png",
    brand: "Canon",
    category: "Lens",
  },
  {
    id: 29,
    name: "Sony FE 70-200mm f/2.8 GM OSS II Lens",
    price: 229990,
    originalPrice: 249990,
    discount: "8% OFF",
    rating: 4.9,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Lenses/Images/254018_0_qxz0bj.png",
    isBestSeller: true,
    brand: "Sony",
    category: "Lens",
  },
  {
    id: 30,
    name: "Nikon NIKKOR Z 50mm f/1.8 S Lens",
    price: 54990,
    originalPrice: 64990,
    discount: "15% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Lenses/Images/223894_0_dqmn0e.png",
    brand: "Nikon",
    category: "Lens",
  },
  {
    id: 31,
    name: "Canon EF 50mm f/1.8 STM Lens",
    price: 11990,
    originalPrice: 13990,
    discount: "14% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Lenses/Images/202658_0_lbdwks.png",
    brand: "Canon",
    category: "Lens",
  },
  {
    id: 32,
    name: "Sony FE 24-105mm f/4 G OSS Lens",
    price: 109990,
    originalPrice: 124990,
    discount: "12% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Cameras/Lenses/Images/219768_0_xj5fkk.png",
    brand: "Sony",
    category: "Lens",
  },

  // --- APPLE CHARGERS ---
  {
    id: 33,
    name: "Apple 20W USB-C Power Adapter",
    price: 1900,
    originalPrice: 2100,
    discount: "10% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobile%20Accessories/Images/226890_1_xmcwfj.png",
    isBestSeller: true,
    brand: "Apple",
    category: "Charger",
  },
  {
    id: 34,
    name: "Apple 35W Dual USB-C Port Power Adapter",
    price: 5590,
    originalPrice: 6100,
    discount: "8% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobile%20Accessories/Images/265102_0_lvmjqv.png",
    brand: "Apple",
    category: "Charger",
  },
  {
    id: 35,
    name: "Apple 140W USB-C Power Adapter",
    price: 9900,
    originalPrice: 10900,
    discount: "9% OFF",
    rating: 4.9,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop%20Chargers%20and%20Adapters/Images/253000_0_fmhvry.png",
    brand: "Apple",
    category: "Charger",
  },
  {
    id: 36,
    name: "Apple MagSafe Charger",
    price: 4500,
    originalPrice: 4900,
    discount: "8% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobile%20Accessories/Images/227839_0_hgwdpm.png",
    isBestSeller: true,
    brand: "Apple",
    category: "Charger",
  },
  {
    id: 37,
    name: "Apple MagSafe Duo Charger",
    price: 14500,
    originalPrice: 15900,
    discount: "9% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobile%20Accessories/Images/231412_0_yxqpor.png",
    brand: "Apple",
    category: "Charger",
  },
  {
    id: 38,
    name: "Apple Watch Magnetic Fast Charger to USB-C Cable",
    price: 2900,
    originalPrice: 3300,
    discount: "12% OFF",
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Wearables/Wearable%20Accessories/Images/253002_0_lvzwij.png",
    brand: "Apple",
    category: "Charger",
  },

  // --- USB PEN DRIVES ---
  {
    id: 39,
    name: "SanDisk Ultra Dual Drive 128GB USB 3.1 Type-C Pen Drive",
    price: 1299,
    originalPrice: 1599,
    discount: "19% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/229048_0_nwfwwo.png",
    isBestSeller: true,
    brand: "SanDisk",
    category: "Storage",
  },
  {
    id: 40,
    name: "SanDisk Ultra Flair 64GB USB 3.0 Pen Drive",
    price: 599,
    originalPrice: 799,
    discount: "25% OFF",
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/204679_0_dw94yp.png",
    brand: "SanDisk",
    category: "Storage",
  },
  {
    id: 41,
    name: "HP v236w 32GB USB 2.0 Pen Drive",
    price: 449,
    originalPrice: 599,
    discount: "25% OFF",
    rating: 4.4,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/247888_0_y53xon.png",
    brand: "HP",
    category: "Storage",
  },
  {
    id: 42,
    name: "Samsung BAR Plus 256GB USB 3.1 Pen Drive",
    price: 2499,
    originalPrice: 2999,
    discount: "17% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/220844_0_otwwve.png",
    isBestSeller: true,
    brand: "Samsung",
    category: "Storage",
  },
  {
    id: 43,
    name: "SanDisk iXpand Flash Drive 128GB for iPhone",
    price: 3999,
    originalPrice: 4599,
    discount: "13% OFF",
    rating: 4.5,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/280917_0_h4xcay.png",
    brand: "SanDisk",
    category: "Storage",
  },
  {
    id: 44,
    name: "Kingston DataTraveler Exodia 64GB USB 3.2 Pen Drive",
    price: 549,
    originalPrice: 699,
    discount: "21% OFF",
    rating: 4.5,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/247891_0_h0kpbb.png",
    brand: "Kingston",
    category: "Storage",
  },
  {
    id: 45,
    name: "SanDisk Cruzer Blade 32GB USB 2.0 Pen Drive",
    price: 399,
    originalPrice: 499,
    discount: "20% OFF",
    rating: 4.4,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Storage%20Devices/Images/202399_0_rz2ubr.png",
    brand: "SanDisk",
    category: "Storage",
  },
];
export default products;
